// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jogrzfpfylkxejhygumk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvZ3J6ZnBmeWxreGVqaHlndW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMTAyMzEsImV4cCI6MjA1MjU4NjIzMX0.yNmVhtf2Pa3X99NjEsCJsyd78tmxG04Di5iXUF1aQew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);